-- Points of interest along the Pan-American Highway: mountains, passes, lakes
CREATE TABLE IF NOT EXISTS route_pois (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  country text NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  wiki_slug text NOT NULL,
  type text NOT NULL CHECK (type IN ('mountain', 'pass', 'lake'))
);

ALTER TABLE route_pois ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON route_pois FOR SELECT USING (true);

INSERT INTO route_pois (name, country, lat, lng, wiki_slug, type) VALUES
-- ── MOUNTAINS ────────────────────────────────────────────────────────────────
('Denali',                     'United States', 63.0690, -151.0070, 'Denali',                          'mountain'),
('Volcán Popocatépetl',        'Mexico',        19.0225,  -98.6278, 'Popocatépetl',                    'mountain'),
('Volcán Iztaccíhuatl',        'Mexico',        19.1795,  -98.6421, 'Iztaccíhuatl',                    'mountain'),
('Volcán Tajumulco',           'Guatemala',     15.0397,  -91.9034, 'Tajumulco',                       'mountain'),
('Volcán Santa Ana',           'El Salvador',   13.8527,  -89.6300, 'Santa_Ana_volcano',               'mountain'),
('Volcán Barú',                'Panama',         8.8081,  -82.5432, 'Volcán_Barú',                     'mountain'),
('Nevado del Ruiz',            'Colombia',       4.8920,  -75.3247, 'Nevado_del_Ruiz',                 'mountain'),
('Volcán Galeras',             'Colombia',       1.2224,  -77.3597, 'Galeras',                         'mountain'),
('Volcán Cayambe',             'Ecuador',        0.0292,  -77.9861, 'Cayambe_(volcano)',                'mountain'),
('Cotopaxi',                   'Ecuador',       -0.6842,  -78.4358, 'Cotopaxi',                        'mountain'),
('Chimborazo',                 'Ecuador',       -1.4690,  -78.8167, 'Chimborazo',                      'mountain'),
('Huascarán',                  'Peru',          -9.1221,  -77.6048, 'Huascarán',                       'mountain'),
('Volcán Misti',               'Peru',         -16.2948,  -71.4088, 'El_Misti',                        'mountain'),
('Nevado Sajama',              'Bolivia',      -18.1025,  -68.8850, 'Sajama_(volcano)',                 'mountain'),
('Nevado Illimani',            'Bolivia',      -16.6381,  -67.7728, 'Illimani',                        'mountain'),
('Aconcagua',                  'Argentina',    -32.6532,  -70.0109, 'Aconcagua',                       'mountain'),
('Ojos del Salado',            'Chile',        -27.1097,  -68.5411, 'Ojos_del_Salado',                 'mountain'),
('Volcán Llaima',              'Chile',        -38.6922,  -71.7294, 'Llaima',                          'mountain'),
('Volcán Villarrica',          'Chile',        -39.4207,  -71.9372, 'Villarrica_(volcano)',             'mountain'),
('Volcán Osorno',              'Chile',        -41.1000,  -72.4939, 'Osorno_(volcano)',                 'mountain'),
('Monte Fitz Roy',             'Argentina',    -49.2728,  -73.0478, 'Fitz_Roy',                        'mountain'),
('Monte Sarmiento',            'Chile',        -54.4333,  -70.8333, 'Monte_Sarmiento',                 'mountain'),
('Volcán Arenal',              'Costa Rica',   10.4626,  -84.7030,  'Arenal_Volcano',                  'mountain'),
('Volcán Irazú',               'Costa Rica',    9.9793,  -83.8525,  'Irazú_Volcano',                   'mountain'),
('Volcán Poás',                'Costa Rica',   10.1985,  -84.2302,  'Poás_Volcano',                    'mountain'),
('Volcán Turrialba',           'Costa Rica',   10.0256,  -83.7675,  'Turrialba_volcano',               'mountain'),
('Volcán Mombacho',            'Nicaragua',    11.8297,  -85.9672,  'Mombacho',                        'mountain'),
('Volcán Concepción',          'Nicaragua',    11.5381,  -85.6225,  'Concepción_(volcano)',             'mountain'),
-- ── PASSES ───────────────────────────────────────────────────────────────────
('Atigun Pass',                'United States', 68.1314, -149.5028, 'Atigun_Pass',                     'pass'),
('Paso Los Libertadores',      'Chile',        -32.8316,  -70.1130, 'Paso_Los_Libertadores',            'pass'),
('Paso Agua Negra',            'Argentina',    -30.2333,  -69.8000, 'Agua_Negra_Pass',                  'pass'),
('Paso San Francisco',         'Chile',        -26.8500,  -68.4500, 'San_Francisco_Pass',               'pass'),
('Paso Jama',                  'Argentina',    -23.2500,  -67.0667, 'Jama_Pass',                        'pass'),
('Paso de Humahuaca',          'Argentina',    -23.2000,  -65.3500, 'Quebrada_de_Humahuaca',            'pass'),
('Paso Pehuenche',             'Chile',        -35.9500,  -70.6333, 'Paso_Pehuenche',                   'pass'),
('Paso Las Leñas',             'Argentina',    -35.1500,  -70.4500, 'Las_Leñas',                        'pass'),
('Paso Cardenal Samoré',       'Chile',        -40.7167,  -71.8667, 'Cardenal_Samoré_Pass',             'pass'),
('Paso Roballos',              'Argentina',    -46.8000,  -71.7000, 'Paso_Roballos',                    'pass'),
('Abra la Raya',               'Peru',         -14.3631,  -70.9694, 'Abra_La_Raya',                     'pass'),
('Paso Chungará',              'Chile',        -18.1667,  -69.1500, 'Lauca_National_Park',              'pass'),
('Cumbre Pass',                'Bolivia',      -16.3500,  -67.8167, 'Cumbre_Pass',                      'pass'),
('Paso de Cortés',             'Mexico',        19.1333,  -98.6500, 'Paso_de_Cortés',                   'pass'),
('Abra Málaga',                'Peru',         -13.3500,  -72.3000, 'Abra_Málaga',                      'pass'),
('Paso Pino Hachado',          'Chile',        -38.6500,  -70.9167, 'Pino_Hachado_Pass',                'pass'),
('Paso Hua Hum',               'Chile',        -40.1500,  -71.6833, 'Paso_Hua_Hum',                     'pass'),
('Paso Vergara',               'Chile',        -37.5833,  -71.0000, 'Paso_Vergara',                     'pass'),
-- ── LAKES ────────────────────────────────────────────────────────────────────
('Lago Titicaca',              'Peru/Bolivia', -15.8402,  -69.3342, 'Lake_Titicaca',                    'lake'),
('Lago Atitlán',               'Guatemala',    14.6909,  -91.2016,  'Lake_Atitlán',                     'lake'),
('Lago de Nicaragua',          'Nicaragua',    11.5294,  -85.3750,  'Lake_Nicaragua',                   'lake'),
('Lago de Managua',            'Nicaragua',    12.2000,  -86.4167,  'Lake_Managua',                     'lake'),
('Lago de Ilopango',           'El Salvador',  13.6667,  -89.0500,  'Lake_Ilopango',                    'lake'),
('Laguna Quilotoa',            'Ecuador',      -0.8565,  -78.9005,  'Quilotoa',                         'lake'),
('Laguna de la Cocha',         'Colombia',      1.0833,  -77.1833,  'La_Cocha_Lagoon',                  'lake'),
('Lago Calima',                'Colombia',      3.9167,  -76.5000,  'Calima_Lake',                      'lake'),
('Lago Poopó',                 'Bolivia',      -18.7833,  -67.1000, 'Lake_Poopó',                       'lake'),
('Salar de Uyuni',             'Bolivia',      -20.2667,  -67.6333, 'Salar_de_Uyuni',                   'lake'),
('Lagunas de Montebello',      'Mexico',        16.1000,  -91.6667, 'Montebello_Lakes_National_Park',   'lake'),
('Lago Villarrica',            'Chile',        -39.2833,  -72.0500, 'Villarrica_Lake',                  'lake'),
('Lago Llanquihue',            'Chile',        -41.1167,  -72.8333, 'Llanquihue_Lake',                  'lake'),
('Lago Todos Los Santos',      'Chile',        -41.0500,  -72.3000, 'Lago_Todos_los_Santos',            'lake'),
('Lago Ranco',                 'Chile',        -40.2167,  -72.3333, 'Lake_Ranco',                       'lake'),
('Lago Nahuel Huapi',          'Argentina',    -40.9000,  -71.5000, 'Nahuel_Huapi_Lake',                'lake'),
('Lago General Carrera',       'Chile',        -46.4500,  -71.8500, 'General_Carrera_Lake',             'lake'),
('Lago O''Higgins',            'Chile',        -48.8000,  -72.5500, 'O''Higgins/San_Martín_Lake',       'lake'),
('Lago Argentino',             'Argentina',    -50.3167,  -72.4500, 'Argentino_Lake',                   'lake'),
('Lago Viedma',                'Argentina',    -49.5333,  -72.5833, 'Viedma_Lake',                      'lake'),
('Lago Cochrane',              'Chile',        -47.2333,  -72.5000, 'Lake_Cochrane',                    'lake'),
('Laguna Chungará',            'Chile',        -18.2333,  -69.1500, 'Chungará_Lake',                    'lake'),
('Laguna Colorada',            'Bolivia',      -22.1833,  -67.7667, 'Laguna_Colorada',                  'lake'),
('Laguna Verde',               'Bolivia',      -22.7833,  -67.8167, 'Laguna_Verde_(Bolivia)',            'lake');
