-- Additional POIs along the Pan-American route (batch 2)
INSERT INTO route_pois (name, country, lat, lng, wiki_slug, type) VALUES
-- ── MOUNTAINS ────────────────────────────────────────────────────────────────
('Volcán Acatenango',      'Guatemala',     14.5014,  -90.8764, 'Acatenango',                      'mountain'),
('Volcán Fuego',           'Guatemala',     14.4733,  -90.8803, 'Fuego_(volcano)',                  'mountain'),
('Volcán Santiaguito',     'Guatemala',     14.7559,  -91.5550, 'Santiaguito',                      'mountain'),
('Volcán Santa María',     'Guatemala',     14.7567,  -91.5522, 'Santa_María_(volcano)',             'mountain'),
('Volcán Masaya',          'Nicaragua',     11.9847,  -86.1611, 'Masaya_Volcano',                   'mountain'),
('Volcán Momotombo',       'Nicaragua',     12.4231,  -86.5400, 'Momotombo',                        'mountain'),
('Cerro Chirripó',         'Costa Rica',     9.4831,  -83.4892, 'Chirripó',                         'mountain'),
('Volcán Calbuco',         'Chile',        -41.3267,  -72.6136, 'Calbuco_(volcano)',                 'mountain'),
('Volcán Hudson',          'Chile',        -45.9000,  -72.9667, 'Hudson_(volcano)',                  'mountain'),
('Cerro Torre',            'Argentina',    -49.3133,  -73.0978, 'Cerro_Torre',                      'mountain'),
('Nevado Coropuna',        'Peru',         -15.5472,  -72.6542, 'Coropuna',                         'mountain'),
('Volcán Tungurahua',      'Ecuador',       -1.4675,  -78.4431, 'Tungurahua_(volcano)',              'mountain'),
('Volcán Antisana',        'Ecuador',       -0.4781,  -78.1417, 'Antisana',                         'mountain'),
('Volcán Pichincha',       'Ecuador',       -0.1717,  -78.5986, 'Pichincha_(volcano)',               'mountain'),
('Nevado del Tolima',      'Colombia',       4.6675,  -75.3981, 'Nevado_del_Tolima',                'mountain'),
('Nevado del Huila',       'Colombia',       2.9283,  -76.0308, 'Nevado_del_Huila',                 'mountain'),
('Volcán Chaitén',         'Chile',        -42.8333,  -72.6500, 'Chaitén_(volcano)',                 'mountain'),
('Volcán Tronador',        'Argentina',    -41.1556,  -71.8878, 'Tronador',                         'mountain'),
('Nevado Sajama',          'Bolivia',      -18.1025,  -68.8850, 'Sajama_(volcano)',                  'mountain'),
-- ── PASSES ───────────────────────────────────────────────────────────────────
('Paso Mamuil Malal',      'Chile',        -39.5667,  -71.5333, 'Mamuil_Malal_Pass',                'pass'),
('Paso Tromen',            'Argentina',    -39.7000,  -71.4500, 'Paso_Tromen',                      'pass'),
('Paso Internacional Los Lagos', 'Chile',  -40.6833,  -72.1000, 'Paso_Los_Lagos',                   'pass'),
('Paso Río Don Guillermo', 'Argentina',    -51.6167,  -72.3667, 'Paso_Río_Don_Guillermo',            'pass'),
('Abra Pampa',             'Argentina',    -22.7214,  -65.6989, 'Abra_Pampa',                       'pass'),
('Paso Huahum',            'Chile',        -40.1500,  -71.6833, 'Paso_Hua_Hum',                     'pass'),
('Abra del Acay',          'Argentina',    -24.4000,  -66.2000, 'Acay_Pass',                        'pass'),
('Paso Puyehue',           'Chile',        -40.6667,  -72.2667, 'Puyehue_Pass',                     'pass'),
('Paso Casas Viejas',      'Chile',        -46.0167,  -71.6667, 'Paso_Casas_Viejas',                'pass'),
('Tres Cruces',            'Chile',        -27.0833,  -68.8167, 'Tres_Cruces_(pass)',                'pass'),
('Paso Portillo',          'Chile',        -33.0000,  -70.1167, 'Paso_Portillo',                    'pass'),
-- ── LAKES ────────────────────────────────────────────────────────────────────
('Laguna de Apoyo',        'Nicaragua',    11.9333,   -86.0333, 'Laguna_de_Apoyo',                  'lake'),
('Lago de Coatepeque',     'El Salvador',  13.8667,   -89.5500, 'Lake_Coatepeque',                  'lake'),
('Lago Calafquén',         'Chile',        -39.5167,  -72.1000, 'Calafquén_Lake',                   'lake'),
('Lago Panguipulli',       'Chile',        -39.7333,  -72.3833, 'Panguipulli_Lake',                 'lake'),
('Lago Yelcho',            'Chile',        -43.3167,  -72.4000, 'Lake_Yelcho',                      'lake'),
('Lago Riesco',            'Chile',        -44.1667,  -72.2500, 'Riesco_Lake_(Chile)',               'lake'),
('Lago Buenos Aires',      'Chile',        -46.5500,  -71.7833, 'General_Carrera_Lake',              'lake'),
('Lago San Martín',        'Argentina',    -48.8333,  -72.3333, 'O''Higgins/San_Martín_Lake',        'lake'),
('Laguna San Rafael',      'Chile',        -46.6333,  -73.8500, 'San_Rafael_Lagoon',                 'lake'),
('Laguna Torre',           'Argentina',    -49.3000,  -73.0167, 'Laguna_Torre',                     'lake'),
('Lago Sarmiento',         'Chile',        -51.0833,  -72.7833, 'Sarmiento_Lake',                   'lake'),
('Lago del Toro',          'Chile',        -51.1667,  -72.7167, 'Lake_del_Toro',                    'lake'),
('Laguna Nimez',           'Argentina',    -50.3500,  -72.2667, 'Laguna_Nimez',                     'lake'),
('Laguna Brava',           'Argentina',    -28.3333,  -68.8833, 'Laguna_Brava,_La_Rioja',            'lake'),
('Laguna de Mucubají',     'Venezuela',     8.7833,   -70.8333, 'Laguna_de_Mucubají',               'lake');
